name: FileBot Build (Windows & Linux)

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Build on Linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Apache Ant
        run: sudo apt-get update && sudo apt-get install -y ant unzip curl

      - name: Install Ivy (for Ant)
        run: |
          mkdir -p ~/.ant/lib
          curl -L -o ~/.ant/lib/ivy.jar https://repo1.maven.org/maven2/org/apache/ivy/ivy/2.5.1/ivy-2.5.1.jar

      - name: Add XZ for Java to Ant
        run: |
          curl -L -o xz.jar https://repo1.maven.org/maven2/org/tukaani/xz/1.9/xz-1.9.jar
          sudo mv xz.jar /usr/share/ant/lib/

      - name: Download OpenJDK 11.0.2
        run: |
          if [ ! -f cache/openjdk-11.0.2_linux-x64_bin.tar.gz ]; then
            curl -L https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz -o cache/openjdk-11.0.2_linux-x64_bin.tar.gz
          fi

      - name: Install JavaFX 11.0.2
        run: |
          if [ ! -f cache/openjfx-11.0.2_linux-x64_bin-sdk.zip ]; then
            curl -L https://download2.gluonhq.com/openjfx/11.0.2/openjfx-11.0.2_linux-x64_bin-sdk.zip -o cache/openjfx-11.0.2_linux-x64_bin-sdk.zip
          fi
          unzip -q cache/openjfx-11.0.2_linux-x64_bin-sdk.zip -d lib/javafx
          echo "JAVA_FX_LIB=$(pwd)/lib/javafx/javafx-sdk-11.0.2/lib" >> $GITHUB_ENV

      - name: Build Linux Artifacts
        run: |
          ant resolve
          ant jar
          ant deb-universal
          ant tar

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-linux-artifacts
          path: |
            dist/*.deb
            dist/*.tar.*

  build-windows:
    runs-on: windows-latest
    name: Build on Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Apache Ant
        run: choco install ant -y

      - name: Install Ivy
        run: |
          mkdir $HOME\.ant\lib
          Invoke-WebRequest https://repo1.maven.org/maven2/org/apache/ivy/ivy/2.5.1/ivy-2.5.1.jar -OutFile $HOME\.ant\lib\ivy.jar

      - name: Install WiX (v4)
        run: dotnet tool install --global wix

      - name: Download OpenJDK 11.0.2
        run: |
          if (!(Test-Path cache\openjdk-11.0.2_windows-x64_bin.zip)) {
            Invoke-WebRequest https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_windows-x64_bin.zip -OutFile cache\openjdk-11.0.2_windows-x64_bin.zip
          }

      - name: Install JavaFX 11.0.2
        run: |
          if (!(Test-Path cache\openjfx-11.0.2_windows-x64_bin-sdk.zip)) {
            Invoke-WebRequest https://download2.gluonhq.com/openjfx/11.0.2/openjfx-11.0.2_windows-x64_bin-sdk.zip -OutFile cache\openjfx-11.0.2_windows-x64_bin-sdk.zip
          }
          mkdir lib\javafx
          Expand-Archive cache\openjfx-11.0.2_windows-x64_bin-sdk.zip -DestinationPath lib\javafx
          echo "JAVA_FX_LIB=$(Resolve-Path lib\javafx\javafx-sdk-11.0.2\lib)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Build Windows Artifacts
        shell: pwsh
        run: |
          ant resolve
          ant jar
          ant msi
          ant zip

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-windows-artifacts
          path: |
            dist/*.msi
            dist/*.zip
